### ISSUE TITLE
Libbacktrace issue with mingw

### ISSUE THREAD

**Issue by jeremy-rifkin** [ianlancetaylor/libbacktrace#111] opened 2023-07-15 00:47 UTC
I'm trying to use libbacktrace with msys2 / mingw-w64 but I'm getting the following output:

```
> g++ -Wall -g .\repro.cpp -lbacktrace -fno-PIE
> .\a.exe
Backtrace error libbacktrace could not find executable to open 0 00000067ad5ffd40
Backtrace error failed to read executable information -1 00000067ad5ffd40
Backtrace error failed to read executable information -1 00000067ad5ffd40
Backtrace error failed to read executable information -1 00000067ad5ffd40
Backtrace error failed to read executable information -1 00000067ad5ffd40
Backtrace error failed to read executable information -1 00000067ad5ffd40
Backtrace error failed to read executable information -1 00000067ad5ffd40
```

I'm using `mingw-w64-ucrt-x86_64-libbacktrace` provided by msys2.

My code is below:

```cpp
#include <iostream>
#include <cstddef>

#include <backtrace.h>

int full_callback(void* data_pointer, uintptr_t address, const char* file, int line, const char* symbol) {
    std::cout
            << file
            << "||"
            << line
            << "||"
            << symbol
            << std::endl;
    return 0;
}

void error_callback(void* data, const char* msg, int errnum) {
    // nothing for now
    fprintf(stderr, "Backtrace error %s %d %p\n", msg, errnum, data);
}

void generate_trace() {
    backtrace_state* state = backtrace_create_state(nullptr, true, error_callback, nullptr);
    backtrace_full(state, 0, full_callback, error_callback, nullptr);
}

void foo() {
    generate_trace();
}

int main() {
    foo();
}

```

Am I doing something wrong?

I've seen other posts and issues where libbacktrace fails due to ASLR, but here it is failing even with -fno-PIE.

**Comment by anarazel** [comment] 2023-07-29 23:02
I suspect this is because you're passing `nullptr` to `backtrace_create_state()`.  It looks like libbacktrace doesn't know how to figure out the filename of the executable on windows.

**Comment by anarazel** [comment] 2023-07-29 23:16
Hm, looks like that'd be reasonably easy to add, using https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-getmodulefilenamea?redirectedfrom=MSDN

@ianlancetaylor Interested in a PR for that? Not a windows person, but the problem reproduces in wine, and I'd not mind useful backtraces from windows CI...

**Comment by ianlancetaylor** [comment] 2023-07-31 02:55
Sure, thanks.

**Comment by ianlancetaylor** [comment] 2023-08-01 20:44
Change committed.

**Closed by ianlancetaylor** 2023-08-01 20:44 UTC
