### ISSUE TITLE
pecoff implementation stripping underscores fails with c++ stacktraces

### ISSUE THREAD

**Issue by Plericromon** [ianlancetaylor/libbacktrace#24] opened 2019-01-24 16:27 UTC
The following line causes underscores to be stripped from function names:

https://github.com/ianlancetaylor/libbacktrace/blob/5a99ff7fed66b8ea8f09c9805c138524a7035ece/pecoff.c#L439

For example boost::stacktrace will run a demangle on the returned symbols from libbacktrace. Without the leading underscore function names will not be demangled. See an example:

Function name in COFF symbol table:
_ZN3foo3Bar6fooBarEv

Function name returned from `backtrace_syminfo` with COFF search function:
ZN3foo3Bar6fooBarEv

While the former can be demangled to foo::Bar::fooBar() the latter cant.

What is the reason for stripping the leading underscore? Would it be possible to avoid this?

**Comment by thanm** [comment] 2019-01-24 16:44
Why are you asking here?

Seems as though this question would be better sent to a GCC forum of some sort. Looking at the GCC source I see that this line was added in the following commit:

[https://github.com/gcc-mirror/gcc/commit/48ee217ec3b4f8e63f33f46b5ecb5894f5052ef7](https://github.com/gcc-mirror/gcc/commit/48ee217ec3b4f8e63f33f46b5ecb5894f5052ef7
)

The person who added this code might have some insights here.

**Comment by Plericromon** [comment] 2019-01-24 16:48
I check this repository out, compile it, use it, a file that is part of this repository does not perform the way I think it should, so I create an issue in that repository. This is pretty much why I am asking here?

Is this repository here not maintained? Or what is the relationship between the files here and on the gcc mirror?

**Comment by ianlancetaylor** [comment] 2019-01-25 03:00
This repository is a stand-alone copy of a library that lives in the GCC sources.

I believe the problem is that 32-bit x86 PE uses a leading underscore bug 64-bit x86_64 PE does not.  Are you using 64-bit PE?

CC @gingold-adacore

**Comment by Plericromon** [comment] 2019-01-25 18:19
Ah, got it. Yes, I am on x86_64, here the _ removal is causing issues. What would be the appropriate place to raise the issue if its not here?

**Comment by ianlancetaylor** [comment] 2019-01-25 19:12
You could file a bug report against gcc/libbacktace at https://gcc.gnu.org/bugzilla.

**Comment by ianlancetaylor** [comment] 2020-09-28 00:41
This is most likely fixed by 2f5efbfa32a698e22aa9560e4bfd0ff4c7cdcbd0.

**Closed by ianlancetaylor** 2020-09-28 00:41 UTC
